// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRzqvXUmIWXzz_NqBinckurYmL3ysBm0',
    appId: '1:649578423390:web:24fb8319c93537d2b480cf',
    messagingSenderId: '649578423390',
    projectId: 'chatapp-ad433',
    authDomain: 'chatapp-ad433.firebaseapp.com',
    storageBucket: 'chatapp-ad433.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3jzxszTPy1yCp-cJ6W_DozzIAqIm59s8',
    appId: '1:649578423390:android:1d9dbbeaae922b0db480cf',
    messagingSenderId: '649578423390',
    projectId: 'chatapp-ad433',
    storageBucket: 'chatapp-ad433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1-JTXl7qdVY_rWDOQbzNEKvP6UVv9_4',
    appId: '1:649578423390:ios:0d657cd1099797aab480cf',
    messagingSenderId: '649578423390',
    projectId: 'chatapp-ad433',
    storageBucket: 'chatapp-ad433.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1-JTXl7qdVY_rWDOQbzNEKvP6UVv9_4',
    appId: '1:649578423390:ios:0d657cd1099797aab480cf',
    messagingSenderId: '649578423390',
    projectId: 'chatapp-ad433',
    storageBucket: 'chatapp-ad433.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRzqvXUmIWXzz_NqBinckurYmL3ysBm0',
    appId: '1:649578423390:web:91e09890f8de7638b480cf',
    messagingSenderId: '649578423390',
    projectId: 'chatapp-ad433',
    authDomain: 'chatapp-ad433.firebaseapp.com',
    storageBucket: 'chatapp-ad433.appspot.com',
  );

}